"""Hardcoded historical data tables for Season.

End-of-regular-season dates and per-year team rosters, extracted from season.py since
these are pure data, not logic, mirroring the _agg_constants.py pattern used elsewhere
in this package.

Both tables require a manual update once per year when a new NHL season begins:
    * regular_season_end_dates: add the new season's final regular-season game date.
    * _TEAMS_BY_YEAR: add the new season's list of team codes.

Season.__init__ raises InvalidSeasonError if a requested season year isn't in
_TEAMS_BY_YEAR, so an unhandled new season fails loudly rather than silently
returning empty data.
"""

regular_season_end_dates = {
    1917: "1918-03-06",
    1918: "1919-02-20",
    1919: "1920-03-13",
    1920: "1921-03-07",
    1921: "1922-03-08",
    1922: "1923-03-05",
    1923: "1924-03-05",
    1924: "1925-03-09",
    1925: "1926-03-17",
    1926: "1927-03-26",
    1927: "1928-03-24",
    1928: "1929-03-17",
    1929: "1930-03-18",
    1930: "1931-03-22",
    1931: "1932-03-22",
    1932: "1933-03-23",
    1933: "1934-03-18",
    1934: "1935-03-19",
    1935: "1936-03-22",
    1936: "1937-03-21",
    1937: "1938-03-20",
    1938: "1939-03-19",
    1939: "1940-03-17",
    1940: "1941-03-18",
    1941: "1942-03-19",
    1942: "1943-03-18",
    1943: "1944-03-19",
    1944: "1945-03-18",
    1945: "1946-03-17",
    1946: "1947-03-23",
    1947: "1948-03-21",
    1948: "1949-03-20",
    1949: "1950-03-26",
    1950: "1951-03-25",
    1951: "1952-03-23",
    1952: "1953-03-22",
    1953: "1954-03-21",
    1954: "1955-03-20",
    1955: "1956-03-18",
    1956: "1957-03-24",
    1957: "1958-03-23",
    1958: "1959-03-22",
    1959: "1960-03-20",
    1960: "1961-03-19",
    1961: "1962-03-25",
    1962: "1963-03-24",
    1963: "1964-03-22",
    1964: "1965-03-28",
    1965: "1966-04-03",
    1966: "1967-04-02",
    1967: "1968-03-31",
    1968: "1969-03-30",
    1969: "1970-04-05",
    1970: "1971-04-04",
    1971: "1972-04-02",
    1972: "1973-04-01",
    1973: "1974-04-07",
    1974: "1975-04-06",
    1975: "1976-04-04",
    1976: "1977-04-03",
    1977: "1978-04-09",
    1978: "1979-04-08",
    1979: "1980-04-06",
    1980: "1981-04-05",
    1981: "1982-04-04",
    1982: "1983-04-03",
    1983: "1984-04-01",
    1984: "1985-04-07",
    1985: "1986-04-06",
    1986: "1987-04-05",
    1987: "1988-04-03",
    1988: "1989-04-02",
    1989: "1990-04-01",
    1990: "1991-03-31",
    1991: "1992-04-16",
    1992: "1993-04-16",
    1993: "1994-04-14",
    1994: "1995-05-03",
    1995: "1996-04-14",
    1996: "1997-04-13",
    1997: "1998-04-19",
    1998: "1999-04-18",
    1999: "2000-04-09",
    2000: "2001-04-08",
    2001: "2002-04-14",
    2002: "2003-04-06",
    2003: "2004-04-04",
    2005: "2006-04-18",
    2006: "2007-04-08",
    2007: "2008-04-06",
    2008: "2009-04-12",
    2009: "2010-04-11",
    2010: "2011-04-10",
    2011: "2012-04-07",
    2012: "2013-04-28",
    2013: "2014-04-13",
    2014: "2015-04-11",
    2015: "2016-04-10",
    2016: "2017-04-09",
    2017: "2018-04-08",
    2018: "2019-04-06",
    2019: "2020-03-11",
    2020: "2021-05-19",
    2021: "2022-05-01",
    2022: "2023-04-14",
    2023: "2024-04-18",
    2024: "2025-04-17",
}


_TEAMS_BY_YEAR: dict[int, list[str]] = {
    1917: ["MTL", "MWN", "SEN"],
    1918: ["MTL", "SEN", "TAN"],
    1919: ["MTL", "QBD", "SEN", "TSP"],
    1920: ["HAM", "MTL", "SEN", "TSP"],
    1921: ["HAM", "MTL", "SEN", "TSP"],
    1922: ["HAM", "MTL", "SEN", "TSP"],
    1923: ["HAM", "MTL", "SEN", "TSP"],
    1924: ["BOS", "HAM", "MMR", "MTL", "SEN", "TSP"],
    1925: ["BOS", "MMR", "MTL", "NYA", "PIR", "SEN", "TSP"],
    1926: ["BOS", "CHI", "DCG", "MMR", "MTL", "NYA", "NYR", "PIR", "SEN", "TSP"],
    1927: ["BOS", "CHI", "DCG", "MMR", "MTL", "NYA", "NYR", "PIR", "SEN", "TOR"],
    1928: ["BOS", "CHI", "DCG", "MMR", "MTL", "NYA", "NYR", "PIR", "SEN", "TOR"],
    1929: ["BOS", "CHI", "DCG", "MMR", "MTL", "NYA", "NYR", "PIR", "SEN", "TOR"],
    1930: ["BOS", "CHI", "DFL", "MMR", "MTL", "NYA", "NYR", "QUA", "SEN", "TOR"],
    1931: ["BOS", "CHI", "DFL", "MMR", "MTL", "NYA", "NYR", "TOR"],
    1932: ["BOS", "CHI", "DET", "MMR", "MTL", "NYA", "NYR", "SEN", "TOR"],
    1933: ["BOS", "CHI", "DET", "MMR", "MTL", "NYA", "NYR", "SEN", "TOR"],
    1934: ["BOS", "CHI", "DET", "MMR", "MTL", "NYA", "NYR", "SLE", "TOR"],
    1935: ["BOS", "CHI", "DET", "MMR", "MTL", "NYA", "NYR", "TOR"],
    1936: ["BOS", "CHI", "DET", "MMR", "MTL", "NYA", "NYR", "TOR"],
    1937: ["BOS", "CHI", "DET", "MMR", "MTL", "NYA", "NYR", "TOR"],
    1938: ["BOS", "CHI", "DET", "MTL", "NYA", "NYR", "TOR"],
    1939: ["BOS", "CHI", "DET", "MTL", "NYA", "NYR", "TOR"],
    1940: ["BOS", "CHI", "DET", "MTL", "NYA", "NYR", "TOR"],
    1941: ["BOS", "BRK", "CHI", "DET", "MTL", "NYR", "TOR"],
    1942: ["BOS", "CHI", "DET", "MTL", "NYR", "TOR"],
    1943: ["BOS", "CHI", "DET", "MTL", "NYR", "TOR"],
    1944: ["BOS", "CHI", "DET", "MTL", "NYR", "TOR"],
    1945: ["BOS", "CHI", "DET", "MTL", "NYR", "TOR"],
    1946: ["BOS", "CHI", "DET", "MTL", "NYR", "TOR"],
    1947: ["BOS", "CHI", "DET", "MTL", "NYR", "TOR"],
    1948: ["BOS", "CHI", "DET", "MTL", "NYR", "TOR"],
    1949: ["BOS", "CHI", "DET", "MTL", "NYR", "TOR"],
    1950: ["BOS", "CHI", "DET", "MTL", "NYR", "TOR"],
    1951: ["BOS", "CHI", "DET", "MTL", "NYR", "TOR"],
    1952: ["BOS", "CHI", "DET", "MTL", "NYR", "TOR"],
    1953: ["BOS", "CHI", "DET", "MTL", "NYR", "TOR"],
    1954: ["BOS", "CHI", "DET", "MTL", "NYR", "TOR"],
    1955: ["BOS", "CHI", "DET", "MTL", "NYR", "TOR"],
    1956: ["BOS", "CHI", "DET", "MTL", "NYR", "TOR"],
    1957: ["BOS", "CHI", "DET", "MTL", "NYR", "TOR"],
    1958: ["BOS", "CHI", "DET", "MTL", "NYR", "TOR"],
    1959: ["BOS", "CHI", "DET", "MTL", "NYR", "TOR"],
    1960: ["BOS", "CHI", "DET", "MTL", "NYR", "TOR"],
    1961: ["BOS", "CHI", "DET", "MTL", "NYR", "TOR"],
    1962: ["BOS", "CHI", "DET", "MTL", "NYR", "TOR"],
    1963: ["BOS", "CHI", "DET", "MTL", "NYR", "TOR"],
    1964: ["BOS", "CHI", "DET", "MTL", "NYR", "TOR"],
    1965: ["BOS", "CHI", "DET", "MTL", "NYR", "TOR"],
    1966: ["BOS", "CHI", "DET", "MTL", "NYR", "TOR"],
    1967: ["BOS", "CHI", "DET", "LAK", "MNS", "MTL", "NYR", "OAK", "PHI", "PIT", "STL", "TOR"],
    1968: ["BOS", "CHI", "DET", "LAK", "MNS", "MTL", "NYR", "OAK", "PHI", "PIT", "STL", "TOR"],
    1969: ["BOS", "CHI", "DET", "LAK", "MNS", "MTL", "NYR", "OAK", "PHI", "PIT", "STL", "TOR"],
    1970: ["BOS", "BUF", "CGS", "CHI", "DET", "LAK", "MNS", "MTL", "NYR", "PHI", "PIT", "STL", "TOR", "VAN"],
    1971: ["BOS", "BUF", "CGS", "CHI", "DET", "LAK", "MNS", "MTL", "NYR", "PHI", "PIT", "STL", "TOR", "VAN"],
    1972: [
        "AFM",
        "BOS",
        "BUF",
        "CGS",
        "CHI",
        "DET",
        "LAK",
        "MNS",
        "MTL",
        "NYI",
        "NYR",
        "PHI",
        "PIT",
        "STL",
        "TOR",
        "VAN",
    ],
    1973: [
        "AFM",
        "BOS",
        "BUF",
        "CGS",
        "CHI",
        "DET",
        "LAK",
        "MNS",
        "MTL",
        "NYI",
        "NYR",
        "PHI",
        "PIT",
        "STL",
        "TOR",
        "VAN",
    ],
    1974: [
        "AFM",
        "BOS",
        "BUF",
        "CGS",
        "CHI",
        "DET",
        "KCS",
        "LAK",
        "MNS",
        "MTL",
        "NYI",
        "NYR",
        "PHI",
        "PIT",
        "STL",
        "TOR",
        "VAN",
        "WSH",
    ],
    1975: [
        "AFM",
        "BOS",
        "BUF",
        "CGS",
        "CHI",
        "DET",
        "KCS",
        "LAK",
        "MNS",
        "MTL",
        "NYI",
        "NYR",
        "PHI",
        "PIT",
        "STL",
        "TOR",
        "VAN",
        "WSH",
    ],
    1976: [
        "AFM",
        "BOS",
        "BUF",
        "CHI",
        "CLE",
        "CLR",
        "DET",
        "LAK",
        "MNS",
        "MTL",
        "NYI",
        "NYR",
        "PHI",
        "PIT",
        "STL",
        "TOR",
        "VAN",
        "WSH",
    ],
    1977: [
        "AFM",
        "BOS",
        "BUF",
        "CHI",
        "CLE",
        "CLR",
        "DET",
        "LAK",
        "MNS",
        "MTL",
        "NYI",
        "NYR",
        "PHI",
        "PIT",
        "STL",
        "TOR",
        "VAN",
        "WSH",
    ],
    1978: [
        "AFM",
        "BOS",
        "BUF",
        "CHI",
        "CLR",
        "DET",
        "LAK",
        "MNS",
        "MTL",
        "NYI",
        "NYR",
        "PHI",
        "PIT",
        "STL",
        "TOR",
        "VAN",
        "WSH",
    ],
    1979: [
        "AFM",
        "BOS",
        "BUF",
        "CHI",
        "CLR",
        "DET",
        "EDM",
        "HFD",
        "LAK",
        "MNS",
        "MTL",
        "NYI",
        "NYR",
        "PHI",
        "PIT",
        "QUE",
        "STL",
        "TOR",
        "VAN",
        "WIN",
        "WSH",
    ],
    1980: [
        "BOS",
        "BUF",
        "CGY",
        "CHI",
        "CLR",
        "DET",
        "EDM",
        "HFD",
        "LAK",
        "MNS",
        "MTL",
        "NYI",
        "NYR",
        "PHI",
        "PIT",
        "QUE",
        "STL",
        "TOR",
        "VAN",
        "WIN",
        "WSH",
    ],
    1981: [
        "BOS",
        "BUF",
        "CGY",
        "CHI",
        "CLR",
        "DET",
        "EDM",
        "HFD",
        "LAK",
        "MNS",
        "MTL",
        "NYI",
        "NYR",
        "PHI",
        "PIT",
        "QUE",
        "STL",
        "TOR",
        "VAN",
        "WIN",
        "WSH",
    ],
    1982: [
        "BOS",
        "BUF",
        "CGY",
        "CHI",
        "DET",
        "EDM",
        "HFD",
        "LAK",
        "MNS",
        "MTL",
        "NJD",
        "NYI",
        "NYR",
        "PHI",
        "PIT",
        "QUE",
        "STL",
        "TOR",
        "VAN",
        "WIN",
        "WSH",
    ],
    1983: [
        "BOS",
        "BUF",
        "CGY",
        "CHI",
        "DET",
        "EDM",
        "HFD",
        "LAK",
        "MNS",
        "MTL",
        "NJD",
        "NYI",
        "NYR",
        "PHI",
        "PIT",
        "QUE",
        "STL",
        "TOR",
        "VAN",
        "WIN",
        "WSH",
    ],
    1984: [
        "BOS",
        "BUF",
        "CGY",
        "CHI",
        "DET",
        "EDM",
        "HFD",
        "LAK",
        "MNS",
        "MTL",
        "NJD",
        "NYI",
        "NYR",
        "PHI",
        "PIT",
        "QUE",
        "STL",
        "TOR",
        "VAN",
        "WIN",
        "WSH",
    ],
    1985: [
        "BOS",
        "BUF",
        "CGY",
        "CHI",
        "DET",
        "EDM",
        "HFD",
        "LAK",
        "MNS",
        "MTL",
        "NJD",
        "NYI",
        "NYR",
        "PHI",
        "PIT",
        "QUE",
        "STL",
        "TOR",
        "VAN",
        "WIN",
        "WSH",
    ],
    1986: [
        "BOS",
        "BUF",
        "CGY",
        "CHI",
        "DET",
        "EDM",
        "HFD",
        "LAK",
        "MNS",
        "MTL",
        "NJD",
        "NYI",
        "NYR",
        "PHI",
        "PIT",
        "QUE",
        "STL",
        "TOR",
        "VAN",
        "WIN",
        "WSH",
    ],
    1987: [
        "BOS",
        "BUF",
        "CGY",
        "CHI",
        "DET",
        "EDM",
        "HFD",
        "LAK",
        "MNS",
        "MTL",
        "NJD",
        "NYI",
        "NYR",
        "PHI",
        "PIT",
        "QUE",
        "STL",
        "TOR",
        "VAN",
        "WIN",
        "WSH",
    ],
    1988: [
        "BOS",
        "BUF",
        "CGY",
        "CHI",
        "DET",
        "EDM",
        "HFD",
        "LAK",
        "MNS",
        "MTL",
        "NJD",
        "NYI",
        "NYR",
        "PHI",
        "PIT",
        "QUE",
        "STL",
        "TOR",
        "VAN",
        "WIN",
        "WSH",
    ],
    1989: [
        "BOS",
        "BUF",
        "CGY",
        "CHI",
        "DET",
        "EDM",
        "HFD",
        "LAK",
        "MNS",
        "MTL",
        "NJD",
        "NYI",
        "NYR",
        "PHI",
        "PIT",
        "QUE",
        "STL",
        "TOR",
        "VAN",
        "WIN",
        "WSH",
    ],
    1990: [
        "BOS",
        "BUF",
        "CGY",
        "CHI",
        "DET",
        "EDM",
        "HFD",
        "LAK",
        "MNS",
        "MTL",
        "NJD",
        "NYI",
        "NYR",
        "PHI",
        "PIT",
        "QUE",
        "STL",
        "TOR",
        "VAN",
        "WIN",
        "WSH",
    ],
    1991: [
        "BOS",
        "BUF",
        "CGY",
        "CHI",
        "DET",
        "EDM",
        "HFD",
        "LAK",
        "MNS",
        "MTL",
        "NJD",
        "NYI",
        "NYR",
        "PHI",
        "PIT",
        "QUE",
        "SJS",
        "STL",
        "TOR",
        "VAN",
        "WIN",
        "WSH",
    ],
    1992: [
        "BOS",
        "BUF",
        "CGY",
        "CHI",
        "DET",
        "EDM",
        "HFD",
        "LAK",
        "MNS",
        "MTL",
        "NJD",
        "NYI",
        "NYR",
        "OTT",
        "PHI",
        "PIT",
        "QUE",
        "SJS",
        "STL",
        "TBL",
        "TOR",
        "VAN",
        "WIN",
        "WSH",
    ],
    1993: [
        "ANA",
        "BOS",
        "BUF",
        "CGY",
        "CHI",
        "DAL",
        "DET",
        "EDM",
        "FLA",
        "HFD",
        "LAK",
        "MTL",
        "NJD",
        "NYI",
        "NYR",
        "OTT",
        "PHI",
        "PIT",
        "QUE",
        "SJS",
        "STL",
        "TBL",
        "TOR",
        "VAN",
        "WIN",
        "WSH",
    ],
    1994: [
        "ANA",
        "BOS",
        "BUF",
        "CGY",
        "CHI",
        "DAL",
        "DET",
        "EDM",
        "FLA",
        "HFD",
        "LAK",
        "MTL",
        "NJD",
        "NYI",
        "NYR",
        "OTT",
        "PHI",
        "PIT",
        "QUE",
        "SJS",
        "STL",
        "TBL",
        "TOR",
        "VAN",
        "WIN",
        "WSH",
    ],
    1995: [
        "ANA",
        "BOS",
        "BUF",
        "CGY",
        "CHI",
        "COL",
        "DAL",
        "DET",
        "EDM",
        "FLA",
        "HFD",
        "LAK",
        "MTL",
        "NJD",
        "NYI",
        "NYR",
        "OTT",
        "PHI",
        "PIT",
        "SJS",
        "STL",
        "TBL",
        "TOR",
        "VAN",
        "WIN",
        "WSH",
    ],
    1996: [
        "ANA",
        "BOS",
        "BUF",
        "CGY",
        "CHI",
        "COL",
        "DAL",
        "DET",
        "EDM",
        "FLA",
        "HFD",
        "LAK",
        "MTL",
        "NJD",
        "NYI",
        "NYR",
        "OTT",
        "PHI",
        "PHX",
        "PIT",
        "SJS",
        "STL",
        "TBL",
        "TOR",
        "VAN",
        "WSH",
    ],
    1997: [
        "ANA",
        "BOS",
        "BUF",
        "CAR",
        "CGY",
        "CHI",
        "COL",
        "DAL",
        "DET",
        "EDM",
        "FLA",
        "LAK",
        "MTL",
        "NJD",
        "NYI",
        "NYR",
        "OTT",
        "PHI",
        "PHX",
        "PIT",
        "SJS",
        "STL",
        "TBL",
        "TOR",
        "VAN",
        "WSH",
    ],
    1998: [
        "ANA",
        "BOS",
        "BUF",
        "CAR",
        "CGY",
        "CHI",
        "COL",
        "DAL",
        "DET",
        "EDM",
        "FLA",
        "LAK",
        "MTL",
        "NJD",
        "NSH",
        "NYI",
        "NYR",
        "OTT",
        "PHI",
        "PHX",
        "PIT",
        "SJS",
        "STL",
        "TBL",
        "TOR",
        "VAN",
        "WSH",
    ],
    1999: [
        "ANA",
        "ATL",
        "BOS",
        "BUF",
        "CAR",
        "CGY",
        "CHI",
        "COL",
        "DAL",
        "DET",
        "EDM",
        "FLA",
        "LAK",
        "MTL",
        "NJD",
        "NSH",
        "NYI",
        "NYR",
        "OTT",
        "PHI",
        "PHX",
        "PIT",
        "SJS",
        "STL",
        "TBL",
        "TOR",
        "VAN",
        "WSH",
    ],
    2000: [
        "ANA",
        "ATL",
        "BOS",
        "BUF",
        "CAR",
        "CBJ",
        "CGY",
        "CHI",
        "COL",
        "DAL",
        "DET",
        "EDM",
        "FLA",
        "LAK",
        "MIN",
        "MTL",
        "NJD",
        "NSH",
        "NYI",
        "NYR",
        "OTT",
        "PHI",
        "PHX",
        "PIT",
        "SJS",
        "STL",
        "TBL",
        "TOR",
        "VAN",
        "WSH",
    ],
    2001: [
        "ANA",
        "ATL",
        "BOS",
        "BUF",
        "CAR",
        "CBJ",
        "CGY",
        "CHI",
        "COL",
        "DAL",
        "DET",
        "EDM",
        "FLA",
        "LAK",
        "MIN",
        "MTL",
        "NJD",
        "NSH",
        "NYI",
        "NYR",
        "OTT",
        "PHI",
        "PHX",
        "PIT",
        "SJS",
        "STL",
        "TBL",
        "TOR",
        "VAN",
        "WSH",
    ],
    2002: [
        "ANA",
        "ATL",
        "BOS",
        "BUF",
        "CAR",
        "CBJ",
        "CGY",
        "CHI",
        "COL",
        "DAL",
        "DET",
        "EDM",
        "FLA",
        "LAK",
        "MIN",
        "MTL",
        "NJD",
        "NSH",
        "NYI",
        "NYR",
        "OTT",
        "PHI",
        "PHX",
        "PIT",
        "SJS",
        "STL",
        "TBL",
        "TOR",
        "VAN",
        "WSH",
    ],
    2003: [
        "ANA",
        "ATL",
        "BOS",
        "BUF",
        "CAR",
        "CBJ",
        "CGY",
        "CHI",
        "COL",
        "DAL",
        "DET",
        "EDM",
        "FLA",
        "LAK",
        "MIN",
        "MTL",
        "NJD",
        "NSH",
        "NYI",
        "NYR",
        "OTT",
        "PHI",
        "PHX",
        "PIT",
        "SJS",
        "STL",
        "TBL",
        "TOR",
        "VAN",
        "WSH",
    ],
    2004: [
        "ANA",
        "ATL",
        "BOS",
        "BUF",
        "CAR",
        "CBJ",
        "CGY",
        "CHI",
        "COL",
        "DAL",
        "DET",
        "EDM",
        "FLA",
        "LAK",
        "MIN",
        "MTL",
        "NJD",
        "NSH",
        "NYI",
        "NYR",
        "OTT",
        "PHI",
        "PHX",
        "PIT",
        "SJS",
        "STL",
        "TBL",
        "TOR",
        "VAN",
        "WSH",
    ],
    2005: [
        "ANA",
        "ATL",
        "BOS",
        "BUF",
        "CAR",
        "CBJ",
        "CGY",
        "CHI",
        "COL",
        "DAL",
        "DET",
        "EDM",
        "FLA",
        "LAK",
        "MIN",
        "MTL",
        "NJD",
        "NSH",
        "NYI",
        "NYR",
        "OTT",
        "PHI",
        "PHX",
        "PIT",
        "SJS",
        "STL",
        "TBL",
        "TOR",
        "VAN",
        "WSH",
    ],
    2006: [
        "ANA",
        "ATL",
        "BOS",
        "BUF",
        "CAR",
        "CBJ",
        "CGY",
        "CHI",
        "COL",
        "DAL",
        "DET",
        "EDM",
        "FLA",
        "LAK",
        "MIN",
        "MTL",
        "NJD",
        "NSH",
        "NYI",
        "NYR",
        "OTT",
        "PHI",
        "PHX",
        "PIT",
        "SJS",
        "STL",
        "TBL",
        "TOR",
        "VAN",
        "WSH",
    ],
    2007: [
        "ANA",
        "ATL",
        "BOS",
        "BUF",
        "CAR",
        "CBJ",
        "CGY",
        "CHI",
        "COL",
        "DAL",
        "DET",
        "EDM",
        "FLA",
        "LAK",
        "MIN",
        "MTL",
        "NJD",
        "NSH",
        "NYI",
        "NYR",
        "OTT",
        "PHI",
        "PHX",
        "PIT",
        "SJS",
        "STL",
        "TBL",
        "TOR",
        "VAN",
        "WSH",
    ],
    2008: [
        "ANA",
        "ATL",
        "BOS",
        "BUF",
        "CAR",
        "CBJ",
        "CGY",
        "CHI",
        "COL",
        "DAL",
        "DET",
        "EDM",
        "FLA",
        "LAK",
        "MIN",
        "MTL",
        "NJD",
        "NSH",
        "NYI",
        "NYR",
        "OTT",
        "PHI",
        "PHX",
        "PIT",
        "SJS",
        "STL",
        "TBL",
        "TOR",
        "VAN",
        "WSH",
    ],
    2009: [
        "ANA",
        "ATL",
        "BOS",
        "BUF",
        "CAR",
        "CBJ",
        "CGY",
        "CHI",
        "COL",
        "DAL",
        "DET",
        "EDM",
        "FLA",
        "LAK",
        "MIN",
        "MTL",
        "NJD",
        "NSH",
        "NYI",
        "NYR",
        "OTT",
        "PHI",
        "PHX",
        "PIT",
        "SJS",
        "STL",
        "TBL",
        "TOR",
        "VAN",
        "WSH",
    ],
    2010: [
        "ANA",
        "ATL",
        "BOS",
        "BUF",
        "CAR",
        "CBJ",
        "CGY",
        "CHI",
        "COL",
        "DAL",
        "DET",
        "EDM",
        "FLA",
        "LAK",
        "MIN",
        "MTL",
        "NJD",
        "NSH",
        "NYI",
        "NYR",
        "OTT",
        "PHI",
        "PHX",
        "PIT",
        "SJS",
        "STL",
        "TBL",
        "TOR",
        "VAN",
        "WSH",
    ],
    2011: [
        "ANA",
        "BOS",
        "BUF",
        "CAR",
        "CBJ",
        "CGY",
        "CHI",
        "COL",
        "DAL",
        "DET",
        "EDM",
        "FLA",
        "LAK",
        "MIN",
        "MTL",
        "NJD",
        "NSH",
        "NYI",
        "NYR",
        "OTT",
        "PHI",
        "PHX",
        "PIT",
        "SJS",
        "STL",
        "TBL",
        "TOR",
        "VAN",
        "WPG",
        "WSH",
    ],
    2012: [
        "ANA",
        "BOS",
        "BUF",
        "CAR",
        "CBJ",
        "CGY",
        "CHI",
        "COL",
        "DAL",
        "DET",
        "EDM",
        "FLA",
        "LAK",
        "MIN",
        "MTL",
        "NJD",
        "NSH",
        "NYI",
        "NYR",
        "OTT",
        "PHI",
        "PHX",
        "PIT",
        "SJS",
        "STL",
        "TBL",
        "TOR",
        "VAN",
        "WPG",
        "WSH",
    ],
    2013: [
        "ANA",
        "BOS",
        "BUF",
        "CAR",
        "CBJ",
        "CGY",
        "CHI",
        "COL",
        "DAL",
        "DET",
        "EDM",
        "FLA",
        "LAK",
        "MIN",
        "MTL",
        "NJD",
        "NSH",
        "NYI",
        "NYR",
        "OTT",
        "PHI",
        "PHX",
        "PIT",
        "SJS",
        "STL",
        "TBL",
        "TOR",
        "VAN",
        "WPG",
        "WSH",
    ],
    2014: [
        "ANA",
        "ARI",
        "BOS",
        "BUF",
        "CAR",
        "CBJ",
        "CGY",
        "CHI",
        "COL",
        "DAL",
        "DET",
        "EDM",
        "FLA",
        "LAK",
        "MIN",
        "MTL",
        "NJD",
        "NSH",
        "NYI",
        "NYR",
        "OTT",
        "PHI",
        "PIT",
        "SJS",
        "STL",
        "TBL",
        "TOR",
        "VAN",
        "WPG",
        "WSH",
    ],
    2015: [
        "ANA",
        "ARI",
        "BOS",
        "BUF",
        "CAR",
        "CBJ",
        "CGY",
        "CHI",
        "COL",
        "DAL",
        "DET",
        "EDM",
        "FLA",
        "LAK",
        "MIN",
        "MTL",
        "NJD",
        "NSH",
        "NYI",
        "NYR",
        "OTT",
        "PHI",
        "PIT",
        "SJS",
        "STL",
        "TBL",
        "TOR",
        "VAN",
        "WPG",
        "WSH",
    ],
    2016: [
        "ANA",
        "ARI",
        "BOS",
        "BUF",
        "CAR",
        "CBJ",
        "CGY",
        "CHI",
        "COL",
        "DAL",
        "DET",
        "EDM",
        "FLA",
        "LAK",
        "MIN",
        "MTL",
        "NJD",
        "NSH",
        "NYI",
        "NYR",
        "OTT",
        "PHI",
        "PIT",
        "SJS",
        "STL",
        "TBL",
        "TOR",
        "VAN",
        "WPG",
        "WSH",
    ],
    2017: [
        "ANA",
        "ARI",
        "BOS",
        "BUF",
        "CAR",
        "CBJ",
        "CGY",
        "CHI",
        "COL",
        "DAL",
        "DET",
        "EDM",
        "FLA",
        "LAK",
        "MIN",
        "MTL",
        "NJD",
        "NSH",
        "NYI",
        "NYR",
        "OTT",
        "PHI",
        "PIT",
        "SJS",
        "STL",
        "TBL",
        "TOR",
        "VAN",
        "VGK",
        "WPG",
        "WSH",
    ],
    2018: [
        "ANA",
        "ARI",
        "BOS",
        "BUF",
        "CAR",
        "CBJ",
        "CGY",
        "CHI",
        "COL",
        "DAL",
        "DET",
        "EDM",
        "FLA",
        "LAK",
        "MIN",
        "MTL",
        "NJD",
        "NSH",
        "NYI",
        "NYR",
        "OTT",
        "PHI",
        "PIT",
        "SJS",
        "STL",
        "TBL",
        "TOR",
        "VAN",
        "VGK",
        "WPG",
        "WSH",
    ],
    2019: [
        "ANA",
        "ARI",
        "BOS",
        "BUF",
        "CAR",
        "CBJ",
        "CGY",
        "CHI",
        "COL",
        "DAL",
        "DET",
        "EDM",
        "FLA",
        "LAK",
        "MIN",
        "MTL",
        "NJD",
        "NSH",
        "NYI",
        "NYR",
        "OTT",
        "PHI",
        "PIT",
        "SJS",
        "STL",
        "TBL",
        "TOR",
        "VAN",
        "VGK",
        "WPG",
        "WSH",
    ],
    2020: [
        "ANA",
        "ARI",
        "BOS",
        "BUF",
        "CAR",
        "CBJ",
        "CGY",
        "CHI",
        "COL",
        "DAL",
        "DET",
        "EDM",
        "FLA",
        "LAK",
        "MIN",
        "MTL",
        "NJD",
        "NSH",
        "NYI",
        "NYR",
        "OTT",
        "PHI",
        "PIT",
        "SJS",
        "STL",
        "TBL",
        "TOR",
        "VAN",
        "VGK",
        "WPG",
        "WSH",
    ],
    2021: [
        "ANA",
        "ARI",
        "BOS",
        "BUF",
        "CAR",
        "CBJ",
        "CGY",
        "CHI",
        "COL",
        "DAL",
        "DET",
        "EDM",
        "FLA",
        "LAK",
        "MIN",
        "MTL",
        "NJD",
        "NSH",
        "NYI",
        "NYR",
        "OTT",
        "PHI",
        "PIT",
        "SEA",
        "SJS",
        "STL",
        "TBL",
        "TOR",
        "VAN",
        "VGK",
        "WPG",
        "WSH",
    ],
    2022: [
        "ANA",
        "ARI",
        "BOS",
        "BUF",
        "CAR",
        "CBJ",
        "CGY",
        "CHI",
        "COL",
        "DAL",
        "DET",
        "EDM",
        "FLA",
        "LAK",
        "MIN",
        "MTL",
        "NJD",
        "NSH",
        "NYI",
        "NYR",
        "OTT",
        "PHI",
        "PIT",
        "SEA",
        "SJS",
        "STL",
        "TBL",
        "TOR",
        "VAN",
        "VGK",
        "WPG",
        "WSH",
    ],
    2023: [
        "ANA",
        "ARI",
        "BOS",
        "BUF",
        "CAR",
        "CBJ",
        "CGY",
        "CHI",
        "COL",
        "DAL",
        "DET",
        "EDM",
        "FLA",
        "LAK",
        "MIN",
        "MTL",
        "NJD",
        "NSH",
        "NYI",
        "NYR",
        "OTT",
        "PHI",
        "PIT",
        "SEA",
        "SJS",
        "STL",
        "TBL",
        "TOR",
        "VAN",
        "VGK",
        "WPG",
        "WSH",
    ],
    2024: [
        "ANA",
        "BOS",
        "BUF",
        "CAN",
        "CAR",
        "CBJ",
        "CGY",
        "CHI",
        "COL",
        "DAL",
        "DET",
        "EDM",
        "FIN",
        "FLA",
        "LAK",
        "MIN",
        "MTL",
        "NJD",
        "NSH",
        "NYI",
        "NYR",
        "OTT",
        "PHI",
        "PIT",
        "SEA",
        "SJS",
        "SWE",
        "STL",
        "TBL",
        "TOR",
        "USA",
        "UTA",
        "VAN",
        "VGK",
        "WPG",
        "WSH",
    ],
    2025: [
        "ANA",
        "BOS",
        "BUF",
        "CAN",
        "CAR",
        "CBJ",
        "CGY",
        "CHI",
        "COL",
        "DAL",
        "DET",
        "EDM",
        "FIN",
        "FLA",
        "LAK",
        "MIN",
        "MTL",
        "NJD",
        "NSH",
        "NYI",
        "NYR",
        "OTT",
        "PHI",
        "PIT",
        "SEA",
        "SJS",
        "SWE",
        "STL",
        "TBL",
        "TOR",
        "USA",
        "UTA",
        "VAN",
        "VGK",
        "WPG",
        "WSH",
    ],
}
