"""Dictionaries used to create pandas and polars pandera schemas.

Includes:
    * pandas_dtype_map - mapping of base datatypes to pandas pandera dtypes
    * polars_dtype_map - mapping of base datatypes to native polars dtypes
    * pandas_pandera_options - options to pass to pandas pandera DataFrameSchema
    * polars_pandera_options - options to pass to polars pandera DataFrameSchema
    * xg_fields - Dictionary of fields used to validate xG training data
    * stats_column_order - tuple of fields to order columns in pandera schema
    * reorder_columns - function to reorder columns to match the base column order
    * basic_info - dictionary of basic information used in all pandera schema (e.g., season, session)
    * ind_stats_info - dictionary of individual stats info used in pandera schemas
    * ind_stats_columns - dictionary of columns used for base individual stats, excluding on-ice stats
    * oi_stats_columns - dictionary of columns used for individual on-ice stats
    * p60_columns - dictionary of columns for per 60 minute statistics
    * percent columns - dictionary of columns for percentage statistics (e.g., xGF vs. xGA)
    * ind_stats_fields - fields used to validate individual statistics, excluding on-ice stats
    * oi_stats_fields - fields used to validate on-ice statistics
    * stats_fields - fields used to validate combined individual statistics, including base, on-ice, per 60, and percent
    * line_stats_info - information used for line statistics
    * line_stats_fields - fields used to validate line statistics, ordered correctly
    * team_stats_info - information used for team statistics
    * team_stats_fields - fields used to validate team statistics, ordered correctly
"""

from __future__ import annotations

import datetime as dt

import pandera.pandas as pa_pd

import polars as pl


# ------------------------------
# Mapping default data types to pandera / native dtypes
# ------------------------------

# pandas types
pandas_dtype_map: dict = {
    int: "Int64",  # Int64 (capital I) supports NaN/None natively
    str: str,
    float: float,
    bool: bool,
    dt.datetime: pa_pd.DateTime,
}

# polars types
polars_dtype_map: dict = {
    int: pl.Int64,
    str: pl.String,
    float: pl.Float64,
    bool: pl.Boolean,
    dt.datetime: pl.Datetime,
    dt.date: pl.Date,
    dt.timedelta: pl.Duration,
}

# ------------------------------
# Dictionaries for pandera options
# ------------------------------

# pandas pandera options
pandas_pandera_options = {
    "coerce": True,
    "ordered": True,
    "unique_column_names": True,
    "add_missing_columns": True,
    "strict": "filter",
}

# polars pandera options, excluding unique_column_names (default polars behaviour) and add_missing_columns
# (column-selection before validate handles absent optional columns; required=False passes validation without them)
_polars_exclude = {"unique_column_names", "add_missing_columns"}
polars_pandera_options = {key: value for key, value in pandas_pandera_options.items() if key not in _polars_exclude}

# ------------------------------
# Setting the default column order, to keep field schema consistent
# ------------------------------

# A list of columns to keep the proper column order for all stats schema
stats_column_order = (
    "season",
    "session",
    "game_id",
    "game_date",
    "player",
    "eh_id",
    "api_id",
    "position",
    "team",
    "opp_team",
    "strength_state",
    "period",
    "score_state",
    "forwards",
    "forwards_eh_id",
    "forwards_api_id",
    "defense",
    "defense_eh_id",
    "defense_api_id",
    "own_goalie",
    "own_goalie_eh_id",
    "own_goalie_api_id",
    "opp_forwards",
    "opp_forwards_eh_id",
    "opp_forwards_api_id",
    "opp_defense",
    "opp_defense_eh_id",
    "opp_defense_api_id",
    "opp_goalie",
    "opp_goalie_eh_id",
    "opp_goalie_api_id",
    "toi",
    "g",
    "g_adj",
    "ihdg",
    "a1",
    "a2",
    "ixg",
    "ixg_adj",
    "base_ixg",
    "base_ixg_adj",
    "context_ixg",
    "isf",
    "isf_adj",
    "ihdsf",
    "imsf",
    "imsf_adj",
    "ihdm",
    "iff",
    "iff_adj",
    "ihdf",
    "isb",
    "isb_adj",
    "icf",
    "icf_adj",
    "ibs",
    "ibs_adj",
    "igive",
    "itake",
    "ihf",
    "iht",
    "ifow",
    "ifol",
    "iozfw",
    "iozfl",
    "inzfw",
    "inzfl",
    "idzfw",
    "idzfl",
    "a1_xg",
    "a2_xg",
    "ipent0",
    "ipent2",
    "ipent4",
    "ipent5",
    "ipent10",
    "ipend0",
    "ipend2",
    "ipend4",
    "ipend5",
    "ipend10",
    "gf",
    "ga",
    "gf_adj",
    "ga_adj",
    "hdgf",
    "hdga",
    "xgf",
    "xga",
    "xgf_adj",
    "xga_adj",
    "base_xgf",
    "base_xgf_adj",
    "base_xga",
    "base_xga_adj",
    "context_xgf",
    "context_xga",
    "sf",
    "sa",
    "sf_adj",
    "sa_adj",
    "hdsf",
    "hdsa",
    "ff",
    "fa",
    "ff_adj",
    "fa_adj",
    "hdff",
    "hdfa",
    "cf",
    "ca",
    "cf_adj",
    "ca_adj",
    "bsf",
    "bsa",
    "bsf_adj",
    "bsa_adj",
    "msf",
    "msa",
    "msf_adj",
    "msa_adj",
    "hdmsf",
    "hdmsa",
    "teammate_block",
    "teammate_block_adj",
    "hf",
    "ht",
    "give",
    "take",
    "ozf",
    "nzf",
    "dzf",
    "fow",
    "fol",
    "ozfw",
    "ozfl",
    "nzfw",
    "nzfl",
    "dzfw",
    "dzfl",
    "pent0",
    "pent2",
    "pent4",
    "pent5",
    "pent10",
    "pend0",
    "pend2",
    "pend4",
    "pend5",
    "pend10",
    "ozs",
    "nzs",
    "dzs",
    "otf",
    "g_p60",
    "g_adj_p60",
    "ihdg_p60",
    "a1_p60",
    "a2_p60",
    "ixg_p60",
    "ixg_adj_p60",
    "base_ixg_p60",
    "base_ixg_adj_p60",
    "context_ixg_p60",
    "isf_p60",
    "isf_adj_p60",
    "ihdsf_p60",
    "imsf_p60",
    "imsf_adj_p60",
    "ihdm_p60",
    "iff_p60",
    "iff_adj_p60",
    "ihdf_p60",
    "isb_p60",
    "isb_adj_p60",
    "icf_p60",
    "icf_adj_p60",
    "ibs_p60",
    "ibs_adj_p60",
    "igive_p60",
    "itake_p60",
    "ihf_p60",
    "iht_p60",
    "a1_xg_p60",
    "a2_xg_p60",
    "ipent0_p60",
    "ipent2_p60",
    "ipent4_p60",
    "ipent5_p60",
    "ipent10_p60",
    "ipend0_p60",
    "ipend2_p60",
    "ipend4_p60",
    "ipend5_p60",
    "ipend10_p60",
    "gf_p60",
    "ga_p60",
    "gf_adj_p60",
    "ga_adj_p60",
    "hdgf_p60",
    "hdga_p60",
    "xgf_p60",
    "xga_p60",
    "xgf_adj_p60",
    "xga_adj_p60",
    "base_xgf_p60",
    "base_xgf_adj_p60",
    "base_xga_p60",
    "base_xga_adj_p60",
    "context_xgf_p60",
    "context_xga_p60",
    "sf_p60",
    "sa_p60",
    "sf_adj_p60",
    "sa_adj_p60",
    "hdsf_p60",
    "hdsa_p60",
    "ff_p60",
    "fa_p60",
    "ff_adj_p60",
    "fa_adj_p60",
    "hdff_p60",
    "hdfa_p60",
    "cf_p60",
    "ca_p60",
    "cf_adj_p60",
    "ca_adj_p60",
    "bsf_p60",
    "bsa_p60",
    "bsf_adj_p60",
    "bsa_adj_p60",
    "msf_p60",
    "msa_p60",
    "msf_adj_p60",
    "msa_adj_p60",
    "hdmsf_p60",
    "hdmsa_p60",
    "teammate_block_p60",
    "teammate_block_adj_p60",
    "hf_p60",
    "ht_p60",
    "give_p60",
    "take_p60",
    "pent0_p60",
    "pent2_p60",
    "pent4_p60",
    "pent5_p60",
    "pent10_p60",
    "pend0_p60",
    "pend2_p60",
    "pend4_p60",
    "pend5_p60",
    "pend10_p60",
    "gf_percent",
    "gf_adj_percent",
    "hdgf_percent",
    "xgf_percent",
    "xgf_adj_percent",
    "base_xgf_percent",
    "base_xgf_adj_percent",
    "context_xgf_percent",
    "sf_percent",
    "sf_adj_percent",
    "hdsf_percent",
    "ff_percent",
    "ff_adj_percent",
    "hdff_percent",
    "cf_percent",
    "cf_adj_percent",
    "bsf_percent",
    "bsf_adj_percent",
    "msf_percent",
    "msf_adj_percent",
    "hdmsf_percent",
    "hf_percent",
    "take_percent",
)


# Function to reorder columns
def reorder_columns(pandera_columns: dict, ordered_columns: tuple = stats_column_order) -> dict:
    """Function to reorder pandera columns."""
    reordered_columns = {key: pandera_columns[key] for key in ordered_columns if key in pandera_columns}

    return reordered_columns


# Basic information used in all pandera schemas
basic_info = {
    "season": {"dtype": int, "nullable": False, "default": False, "required": True},
    "session": {"dtype": str, "nullable": False, "default": False, "required": True},
    "game_id": {"dtype": int, "nullable": False, "default": False, "required": False},
    "game_date": {"dtype": str, "nullable": False, "default": False, "required": False},
}

# Individual stats columns
ind_stats_info = {
    "player": {"dtype": str, "nullable": False, "default": False, "required": True},
    "eh_id": {"dtype": str, "nullable": False, "default": False, "required": True},
    "api_id": {"dtype": int, "nullable": False, "default": False, "required": True},
    "position": {"dtype": str, "nullable": False, "default": False, "required": True},
    "team": {"dtype": str, "nullable": False, "default": False, "required": True},
    "opp_team": {"dtype": str, "nullable": False, "default": False, "required": False},
    "strength_state": {"dtype": str, "nullable": False, "default": False, "required": False},
    "period": {"dtype": int, "nullable": False, "default": False, "required": False},
    "score_state": {"dtype": str, "nullable": False, "default": False, "required": False},
    "forwards": {"dtype": str, "nullable": True, "default": False, "required": False},
    "forwards_eh_id": {"dtype": str, "nullable": True, "default": False, "required": False},
    "forwards_api_id": {"dtype": str, "nullable": True, "default": False, "required": False},
    "defense": {"dtype": str, "nullable": True, "default": False, "required": False},
    "defense_eh_id": {"dtype": str, "nullable": True, "default": False, "required": False},
    "defense_api_id": {"dtype": str, "nullable": True, "default": False, "required": False},
    "own_goalie": {"dtype": str, "nullable": True, "default": False, "required": False},
    "own_goalie_eh_id": {"dtype": str, "nullable": True, "default": False, "required": False},
    "own_goalie_api_id": {"dtype": int, "nullable": True, "default": False, "required": False},
    "opp_forwards": {"dtype": str, "nullable": True, "default": False, "required": False},
    "opp_forwards_eh_id": {"dtype": str, "nullable": True, "default": False, "required": False},
    "opp_forwards_api_id": {"dtype": str, "nullable": True, "default": False, "required": False},
    "opp_defense": {"dtype": str, "nullable": True, "default": False, "required": False},
    "opp_defense_eh_id": {"dtype": str, "nullable": True, "default": False, "required": False},
    "opp_defense_api_id": {"dtype": str, "nullable": True, "default": False, "required": False},
    "opp_goalie": {"dtype": str, "nullable": True, "default": False, "required": False},
    "opp_goalie_eh_id": {"dtype": str, "nullable": True, "default": False, "required": False},
    "opp_goalie_api_id": {"dtype": int, "nullable": True, "default": False, "required": False},
}

ind_stats_columns = {
    "g": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "g_adj": {"dtype": float, "nullable": False, "default": 0, "required": True},
    "ihdg": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "a1": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "a2": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "ixg": {"dtype": float, "nullable": False, "default": 0, "required": True},
    "ixg_adj": {"dtype": float, "nullable": False, "default": 0, "required": True},
    "base_ixg": {"dtype": float, "nullable": True, "default": False, "required": False},
    "base_ixg_adj": {"dtype": float, "nullable": True, "default": False, "required": False},
    "context_ixg": {"dtype": float, "nullable": True, "default": False, "required": False},
    "isf": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "isf_adj": {"dtype": float, "nullable": False, "default": 0, "required": True},
    "ihdsf": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "imsf": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "imsf_adj": {"dtype": float, "nullable": False, "default": 0, "required": True},
    "ihdm": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "iff": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "iff_adj": {"dtype": float, "nullable": False, "default": 0, "required": True},
    "ihdf": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "isb": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "isb_adj": {"dtype": float, "nullable": False, "default": 0, "required": True},
    "icf": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "icf_adj": {"dtype": float, "nullable": False, "default": 0, "required": True},
    "ibs": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "ibs_adj": {"dtype": float, "nullable": False, "default": 0, "required": True},
    "igive": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "itake": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "ihf": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "iht": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "ifow": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "ifol": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "iozfw": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "iozfl": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "inzfw": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "inzfl": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "idzfw": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "idzfl": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "a1_xg": {"dtype": float, "nullable": False, "default": 0, "required": True},
    "a2_xg": {"dtype": float, "nullable": False, "default": 0, "required": True},
    "ipent0": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "ipent2": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "ipent4": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "ipent5": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "ipent10": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "ipend0": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "ipend2": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "ipend4": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "ipend5": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "ipend10": {"dtype": int, "nullable": False, "default": 0, "required": True},
}

oi_stats_columns = {
    "toi": {"dtype": float, "nullable": False, "default": 0, "required": True},
    "gf": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "ga": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "gf_adj": {"dtype": float, "nullable": False, "default": 0, "required": True},
    "ga_adj": {"dtype": float, "nullable": False, "default": 0, "required": True},
    "hdgf": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "hdga": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "xgf": {"dtype": float, "nullable": False, "default": 0, "required": True},
    "xga": {"dtype": float, "nullable": False, "default": 0, "required": True},
    "xgf_adj": {"dtype": float, "nullable": False, "default": 0, "required": True},
    "xga_adj": {"dtype": float, "nullable": False, "default": 0, "required": True},
    "base_xgf": {"dtype": float, "nullable": True, "default": False, "required": False},
    "base_xgf_adj": {"dtype": float, "nullable": True, "default": False, "required": False},
    "base_xga": {"dtype": float, "nullable": True, "default": False, "required": False},
    "base_xga_adj": {"dtype": float, "nullable": True, "default": False, "required": False},
    "context_xgf": {"dtype": float, "nullable": True, "default": False, "required": False},
    "context_xga": {"dtype": float, "nullable": True, "default": False, "required": False},
    "sf": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "sa": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "sf_adj": {"dtype": float, "nullable": False, "default": 0, "required": True},
    "sa_adj": {"dtype": float, "nullable": False, "default": 0, "required": True},
    "hdsf": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "hdsa": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "ff": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "fa": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "ff_adj": {"dtype": float, "nullable": False, "default": 0, "required": True},
    "fa_adj": {"dtype": float, "nullable": False, "default": 0, "required": True},
    "hdff": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "hdfa": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "cf": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "ca": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "cf_adj": {"dtype": float, "nullable": False, "default": 0, "required": True},
    "ca_adj": {"dtype": float, "nullable": False, "default": 0, "required": True},
    "bsf": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "bsa": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "bsf_adj": {"dtype": float, "nullable": False, "default": 0, "required": True},
    "bsa_adj": {"dtype": float, "nullable": False, "default": 0, "required": True},
    "msf": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "msa": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "msf_adj": {"dtype": float, "nullable": False, "default": 0, "required": True},
    "msa_adj": {"dtype": float, "nullable": False, "default": 0, "required": True},
    "hdmsf": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "hdmsa": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "teammate_block": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "teammate_block_adj": {"dtype": float, "nullable": False, "default": 0, "required": True},
    "hf": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "ht": {"dtype": int, "nullable": False, "default": 0, "required": True},
    # "give": {"dtype": int, "nullable": False, "default": 0, "required": True},
    # "take": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "ozf": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "nzf": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "dzf": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "fow": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "fol": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "ozfw": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "ozfl": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "nzfw": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "nzfl": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "dzfw": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "dzfl": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "pent0": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "pent2": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "pent4": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "pent5": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "pent10": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "pend0": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "pend2": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "pend4": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "pend5": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "pend10": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "ozs": {"dtype": int, "nullable": False, "default": False, "required": False},
    "nzs": {"dtype": int, "nullable": False, "default": False, "required": False},
    "dzs": {"dtype": int, "nullable": False, "default": False, "required": False},
    "otf": {"dtype": int, "nullable": False, "default": False, "required": False},
}

# Stats per 60 minute columns
p60_columns = {
    "g_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "g_adj_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "ihdg_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "a1_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "a2_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "ixg_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "ixg_adj_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "base_ixg_p60": {"dtype": float, "nullable": True, "default": False, "required": False},
    "base_ixg_adj_p60": {"dtype": float, "nullable": True, "default": False, "required": False},
    "context_ixg_p60": {"dtype": float, "nullable": True, "default": False, "required": False},
    "isf_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "isf_adj_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "ihdsf_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "imsf_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "imsf_adj_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "ihdm_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "iff_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "iff_adj_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "ihdf_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "isb_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "isb_adj_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "icf_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "icf_adj_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "ibs_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "ibs_adj_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "igive_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "itake_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "ihf_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "iht_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "a1_xg_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "a2_xg_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "ipent0_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "ipent2_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "ipent4_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "ipent5_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "ipent10_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "ipend0_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "ipend2_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "ipend4_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "ipend5_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "ipend10_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "gf_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "ga_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "gf_adj_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "ga_adj_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "hdgf_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "hdga_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "xgf_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "xga_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "xgf_adj_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "xga_adj_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "base_xgf_p60": {"dtype": float, "nullable": True, "default": False, "required": False},
    "base_xgf_adj_p60": {"dtype": float, "nullable": True, "default": False, "required": False},
    "base_xga_p60": {"dtype": float, "nullable": True, "default": False, "required": False},
    "base_xga_adj_p60": {"dtype": float, "nullable": True, "default": False, "required": False},
    "context_xgf_p60": {"dtype": float, "nullable": True, "default": False, "required": False},
    "context_xga_p60": {"dtype": float, "nullable": True, "default": False, "required": False},
    "sf_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "sa_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "sf_adj_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "sa_adj_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "hdsf_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "hdsa_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "ff_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "fa_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "ff_adj_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "fa_adj_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "hdff_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "hdfa_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "cf_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "ca_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "cf_adj_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "ca_adj_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "bsf_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "bsa_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "bsf_adj_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "bsa_adj_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "msf_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "msa_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "msf_adj_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "msa_adj_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "hdmsf_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "hdmsa_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "teammate_block_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "hf_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "ht_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    # "give_p60": {"dtype": float, "nullable": False, "default": 0, "required": True},
    # "take_p60": {"dtype": float, "nullable": False, "default": 0, "required": True},
    "pent0_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "pent2_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "pent4_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "pent5_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "pent10_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "pend0_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "pend2_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "pend4_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "pend5_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "pend10_p60": {"dtype": float, "nullable": True, "default": 0, "required": True},
}

# For / against percentage columns
percent_columns = {
    "gf_percent": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "gf_adj_percent": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "hdgf_percent": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "xgf_percent": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "xgf_adj_percent": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "base_xgf_percent": {"dtype": float, "nullable": True, "default": False, "required": False},
    "base_xgf_adj_percent": {"dtype": float, "nullable": True, "default": False, "required": False},
    "context_xgf_percent": {"dtype": float, "nullable": True, "default": False, "required": False},
    "sf_percent": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "sf_adj_percent": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "hdsf_percent": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "ff_percent": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "ff_adj_percent": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "hdff_percent": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "cf_percent": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "cf_adj_percent": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "bsf_percent": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "bsf_adj_percent": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "msf_percent": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "msf_adj_percent": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "hdmsf_percent": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "hf_percent": {"dtype": float, "nullable": True, "default": 0, "required": True},
    "take_percent": {"dtype": float, "nullable": False, "default": 0, "required": True},
}

# Columns used for individual stats (these are the basic ones that are not combined with on-ice stats)
ind_stats_fields = reorder_columns({**basic_info, **ind_stats_info, **ind_stats_columns})

# Columns used for on-ice stats (these are the basic ones that are not combined with the individual stats)
oi_stats_fields = reorder_columns({**basic_info, **ind_stats_info, **oi_stats_columns})

# Columns for combined individual stats, including both the individual and on-ice statistics
stats_fields = reorder_columns(
    {**basic_info, **ind_stats_info, **ind_stats_columns, **oi_stats_columns, **p60_columns, **percent_columns}
)

# Setting up team and line stats
team_and_line_stats_p60_percent = {
    key: value
    for key, value in {**p60_columns, **percent_columns}.items()
    if key.replace("_p60", "").replace("_percent", "") in list(oi_stats_columns.keys())
}

# Info columns specifically for the line stats schema
line_stats_info = [
    "team",
    "opp_team",
    "strength_state",
    "period",
    "score_state",
    "forwards",
    "forwards_eh_id",
    "forwards_api_id",
    "defense",
    "defense_eh_id",
    "defense_api_id",
    "own_goalie",
    "own_goalie_eh_id",
    "own_goalie_api_id",
    "opp_forwards",
    "opp_forwards_eh_id",
    "opp_forwards_api_id",
    "opp_defense",
    "opp_defense_eh_id",
    "opp_defense_api_id",
    "opp_goalie",
    "opp_goalie_eh_id",
    "opp_goalie_api_id",
]

# Collecting line stats info columns from the individual stats info columns
line_stats_info = {key: value for key, value in ind_stats_info.items() if key in line_stats_info}

# Columns for line stats
line_stats_fields = reorder_columns(
    {**basic_info, **line_stats_info, **oi_stats_columns, **team_and_line_stats_p60_percent}
)

# Info columns specifically for the team stats schema
team_stats_info = ["team", "opp_team", "strength_state", "period", "score_state"]

# Collecting team stats info columns from the individual stats info columns
team_stats_info = {key: value for key, value in ind_stats_info.items() if key in team_stats_info}

# Columns for team stats
team_stats_fields = reorder_columns(
    {**basic_info, **team_stats_info, **oi_stats_columns, **team_and_line_stats_p60_percent}
)
