import datetime as dt

from chickenstats.chicken_nhl._validation_schema import (
    ind_stats_fields,
    oi_stats_fields,
    stats_fields,
    line_stats_fields,
    team_stats_fields,
)

pbp_fields: dict = {
    "id": {"dtype": int, "nullable": False, "default": False, "required": True},
    "season": {"dtype": int, "nullable": False, "default": False, "required": True},
    "session": {"dtype": str, "nullable": False, "default": False, "required": True},
    "game_id": {"dtype": int, "nullable": False, "default": False, "required": True},
    "game_date": {"dtype": str, "nullable": False, "default": False, "required": True},
    "event_index": {"dtype": int, "nullable": False, "default": False, "required": True},
    "period": {"dtype": int, "nullable": False, "default": False, "required": True},
    "period_seconds": {"dtype": int, "nullable": False, "default": False, "required": True},
    "game_seconds": {"dtype": int, "nullable": False, "default": False, "required": True},
    "clock_time": {"dtype": str, "nullable": False, "default": False, "required": True},
    "strength_state": {"dtype": str, "nullable": True, "default": False, "required": True},
    "event_team": {"dtype": str, "nullable": True, "default": False, "required": True},
    "opp_team": {"dtype": str, "nullable": True, "default": False, "required": True},
    "event_type": {"dtype": str, "nullable": False, "default": False, "required": True},
    "event_description": {"dtype": str, "nullable": True, "default": False, "required": True},
    "event_detail": {"dtype": str, "nullable": True, "default": False, "required": True},
    "event_zone": {"dtype": str, "nullable": True, "default": False, "required": True},
    "coords_x": {"dtype": float, "nullable": True, "default": False, "required": True},
    "coords_y": {"dtype": float, "nullable": True, "default": False, "required": True},
    "high_danger": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "danger": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "event_player_1": {"dtype": str, "nullable": True, "default": False, "required": True},
    "event_player_1_eh_id": {"dtype": str, "nullable": True, "default": False, "required": True},
    "event_player_1_pos": {"dtype": str, "nullable": True, "default": False, "required": True},
    "event_player_2": {"dtype": str, "nullable": True, "default": False, "required": True},
    "event_player_2_eh_id": {"dtype": str, "nullable": True, "default": False, "required": True},
    "event_player_2_pos": {"dtype": str, "nullable": True, "default": False, "required": True},
    "event_player_3": {"dtype": str, "nullable": True, "default": False, "required": True},
    "event_player_3_eh_id": {"dtype": str, "nullable": True, "default": False, "required": True},
    "event_player_3_pos": {"dtype": str, "nullable": True, "default": False, "required": True},
    "score_state": {"dtype": str, "nullable": True, "default": False, "required": True},
    "event_length": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "event_distance": {"dtype": float, "nullable": True, "default": False, "required": True},
    "pbp_distance": {"dtype": float, "nullable": True, "default": False, "required": True},
    "event_angle": {"dtype": float, "nullable": True, "default": False, "required": True},
    "home_score": {"dtype": int, "nullable": True, "default": False, "required": False},
    "away_score": {"dtype": int, "nullable": True, "default": False, "required": False},
    "is_home": {"dtype": int, "nullable": True, "default": False, "required": True},
    "home_team": {"dtype": str, "nullable": True, "default": False, "required": False},
    "away_team": {"dtype": str, "nullable": True, "default": False, "required": False},
    "home_skaters": {"dtype": int, "nullable": True, "default": False, "required": False},
    "away_skaters": {"dtype": int, "nullable": True, "default": False, "required": False},
    "home_zone": {"dtype": str, "required": False, "default": False, "nullable": True},
    "home_goalie": {"dtype": str, "nullable": True, "default": False, "required": False},
    "away_goalie": {"dtype": str, "nullable": True, "default": False, "required": False},
    "home_zonestart": {"dtype": float, "nullable": True, "default": False, "required": False},
    "face_index": {"dtype": int, "nullable": True, "default": False, "required": False},
    "pen_index": {"dtype": int, "nullable": True, "default": False, "required": False},
    "shift_index": {"dtype": int, "nullable": True, "default": False, "required": False},
    "game_score_state": {"dtype": str, "nullable": True, "default": False, "required": False},
    "game_strength_state": {"dtype": str, "nullable": True, "default": False, "required": False},
    "forwards": {"dtype": str, "nullable": True, "default": False, "required": False},
    "forwards_eh_id": {"dtype": str, "nullable": True, "default": False, "required": False},
    "defense": {"dtype": str, "nullable": True, "default": False, "required": False},
    "defense_eh_id": {"dtype": str, "nullable": True, "default": False, "required": False},
    "own_goalie": {"dtype": str, "nullable": True, "default": False, "required": False},
    "own_goalie_eh_id": {"dtype": str, "nullable": True, "default": False, "required": False},
    "event_on_1": {"dtype": str, "nullable": True, "default": False, "required": False},
    "event_on_1_eh_id": {"dtype": str, "nullable": True, "default": False, "required": False},
    "event_on_1_pos": {"dtype": str, "nullable": True, "default": False, "required": False},
    "event_on_2": {"dtype": str, "nullable": True, "default": False, "required": False},
    "event_on_2_eh_id": {"dtype": str, "nullable": True, "default": False, "required": False},
    "event_on_2_pos": {"dtype": str, "nullable": True, "default": False, "required": False},
    "event_on_3": {"dtype": str, "nullable": True, "default": False, "required": False},
    "event_on_3_eh_id": {"dtype": str, "nullable": True, "default": False, "required": False},
    "event_on_3_pos": {"dtype": str, "nullable": True, "default": False, "required": False},
    "event_on_4": {"dtype": str, "nullable": True, "default": False, "required": False},
    "event_on_4_eh_id": {"dtype": str, "nullable": True, "default": False, "required": False},
    "event_on_4_pos": {"dtype": str, "nullable": True, "default": False, "required": False},
    "event_on_5": {"dtype": str, "nullable": True, "default": False, "required": False},
    "event_on_5_eh_id": {"dtype": str, "nullable": True, "default": False, "required": False},
    "event_on_5_pos": {"dtype": str, "nullable": True, "default": False, "required": False},
    "event_on_6": {"dtype": str, "nullable": True, "default": False, "required": False},
    "event_on_6_eh_id": {"dtype": str, "nullable": True, "default": False, "required": False},
    "event_on_6_pos": {"dtype": str, "nullable": True, "default": False, "required": False},
    "event_on_7": {"dtype": str, "nullable": True, "default": False, "required": False},
    "event_on_7_eh_id": {"dtype": str, "nullable": True, "default": False, "required": False},
    "event_on_7_pos": {"dtype": str, "nullable": True, "default": False, "required": False},
    "opp_strength_state": {"dtype": str, "nullable": True, "default": False, "required": False},
    "opp_score_state": {"dtype": str, "nullable": True, "default": False, "required": False},
    "opp_forwards": {"dtype": str, "nullable": True, "default": False, "required": False},
    "opp_forwards_eh_id": {"dtype": str, "nullable": True, "default": False, "required": False},
    "opp_defense": {"dtype": str, "nullable": True, "default": False, "required": False},
    "opp_defense_eh_id": {"dtype": str, "nullable": True, "default": False, "required": False},
    "opp_goalie": {"dtype": str, "nullable": True, "default": False, "required": False},
    "opp_goalie_eh_id": {"dtype": str, "nullable": True, "default": False, "required": False},
    "opp_on_1": {"dtype": str, "nullable": True, "default": False, "required": False},
    "opp_on_1_eh_id": {"dtype": str, "nullable": True, "default": False, "required": False},
    "opp_on_1_pos": {"dtype": str, "nullable": True, "default": False, "required": False},
    "opp_on_2": {"dtype": str, "nullable": True, "default": False, "required": False},
    "opp_on_2_eh_id": {"dtype": str, "nullable": True, "default": False, "required": False},
    "opp_on_2_pos": {"dtype": str, "nullable": True, "default": False, "required": False},
    "opp_on_3": {"dtype": str, "nullable": True, "default": False, "required": False},
    "opp_on_3_eh_id": {"dtype": str, "nullable": True, "default": False, "required": False},
    "opp_on_3_pos": {"dtype": str, "nullable": True, "default": False, "required": False},
    "opp_on_4": {"dtype": str, "nullable": True, "default": False, "required": False},
    "opp_on_4_eh_id": {"dtype": str, "nullable": True, "default": False, "required": False},
    "opp_on_4_pos": {"dtype": str, "nullable": True, "default": False, "required": False},
    "opp_on_5": {"dtype": str, "nullable": True, "default": False, "required": False},
    "opp_on_5_eh_id": {"dtype": str, "nullable": True, "default": False, "required": False},
    "opp_on_5_pos": {"dtype": str, "nullable": True, "default": False, "required": False},
    "opp_on_6": {"dtype": str, "nullable": True, "default": False, "required": False},
    "opp_on_6_eh_id": {"dtype": str, "nullable": True, "default": False, "required": False},
    "opp_on_6_pos": {"dtype": str, "nullable": True, "default": False, "required": False},
    "opp_on_7": {"dtype": str, "nullable": True, "default": False, "required": False},
    "opp_on_7_eh_id": {"dtype": str, "nullable": True, "default": False, "required": False},
    "opp_on_7_pos": {"dtype": str, "nullable": True, "default": False, "required": False},
    "num_on": {"dtype": float, "nullable": True, "default": False, "required": True},
    "num_off": {"dtype": float, "nullable": True, "default": False, "required": True},
    "players_on": {"dtype": str, "nullable": True, "default": False, "required": False},
    "players_on_eh_id": {"dtype": str, "nullable": True, "default": False, "required": False},
    "players_on_pos": {"dtype": str, "nullable": True, "default": False, "required": False},
    "players_off": {"dtype": str, "nullable": True, "default": False, "required": False},
    "players_off_eh_id": {"dtype": str, "nullable": True, "default": False, "required": False},
    "players_off_pos": {"dtype": str, "nullable": True, "default": False, "required": False},
    "zone_start": {"dtype": str, "nullable": True, "default": False, "required": False},
    "goal": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "hd_goal": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "goal_adj": {"dtype": float, "nullable": False, "default": 0, "required": True},
    "pred_goal": {"dtype": float, "nullable": True, "default": False, "required": True},
    "pred_goal_adj": {"dtype": float, "nullable": True, "default": False, "required": True},
    "shot": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "hd_shot": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "shot_adj": {"dtype": float, "nullable": False, "default": 0, "required": True},
    "miss": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "miss_adj": {"dtype": float, "nullable": False, "default": 0, "required": True},
    "hd_miss": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "fenwick": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "hd_fenwick": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "fenwick_adj": {"dtype": float, "nullable": False, "default": 0, "required": True},
    "corsi": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "corsi_adj": {"dtype": float, "nullable": False, "default": 0, "required": True},
    "block": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "block_adj": {"dtype": float, "nullable": False, "default": 0, "required": True},
    "hit": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "give": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "take": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "fac": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "pen0": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "pen2": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "pen4": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "pen5": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "pen10": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "change": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "stop": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "ozf": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "nzf": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "dzf": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "ozs": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "nzs": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "dzs": {"dtype": int, "nullable": False, "default": 0, "required": True},
    "otf": {"dtype": int, "nullable": False, "default": 0, "required": True},
}

gar_fields: dict = {
    "player": {"dtype": str, "nullable": False, "default": False, "required": True},
    "eh_id": {"dtype": str, "nullable": False, "default": False, "required": True},
    "api_id": {"dtype": int, "nullable": True, "default": False, "required": True},
    "season": {"dtype": str, "nullable": False, "default": False, "required": True},
    "team": {"dtype": str, "nullable": False, "default": False, "required": True},
    "position": {"dtype": str, "nullable": False, "default": False, "required": True},
    # Skater-only
    "shoots": {"dtype": str, "nullable": True, "default": False, "required": False},
    # Goalie-only
    "catches": {"dtype": str, "nullable": True, "default": False, "required": False},
    "birthday": {"dtype": dt.date, "nullable": True, "default": False, "required": True},
    "age": {"dtype": int, "nullable": True, "default": False, "required": True},
    "draft_yr": {"dtype": int, "nullable": True, "default": False, "required": False},
    "draft_rd": {"dtype": str, "nullable": True, "default": False, "required": False},
    "draft_ov": {"dtype": str, "nullable": True, "default": False, "required": False},
    "gp": {"dtype": int, "nullable": True, "default": False, "required": True},
    # Skater-only
    "toi_all": {"dtype": float, "nullable": True, "default": False, "required": False},
    "toi_ev": {"dtype": float, "nullable": True, "default": False, "required": True},
    # Skater-only
    "toi_pp": {"dtype": float, "nullable": True, "default": False, "required": False},
    "toi_sh": {"dtype": float, "nullable": True, "default": False, "required": True},
    # Goalie-only
    "fa_ev": {"dtype": int, "nullable": True, "default": False, "required": False},
    "fa_sh": {"dtype": int, "nullable": True, "default": False, "required": False},
    # Skater-only
    "evo_gar": {"dtype": float, "nullable": True, "default": False, "required": False},
    "evd_gar": {"dtype": float, "nullable": True, "default": False, "required": True},
    # Skater-only
    "ppo_gar": {"dtype": float, "nullable": True, "default": False, "required": False},
    "shd_gar": {"dtype": float, "nullable": True, "default": False, "required": True},
    "take_gar": {"dtype": float, "nullable": True, "default": False, "required": True},
    "draw_gar": {"dtype": float, "nullable": True, "default": False, "required": True},
    # Skater-only
    "off_gar": {"dtype": float, "nullable": True, "default": False, "required": False},
    "def_gar": {"dtype": float, "nullable": True, "default": False, "required": False},
    "pens_gar": {"dtype": float, "nullable": True, "default": False, "required": False},
    "gar": {"dtype": float, "nullable": True, "default": False, "required": True},
    "war": {"dtype": float, "nullable": True, "default": False, "required": True},
    "spar": {"dtype": float, "nullable": True, "default": False, "required": True},
}

xgar_fields: dict = {
    "player": {"dtype": str, "nullable": False, "default": False, "required": True},
    "eh_id": {"dtype": str, "nullable": False, "default": False, "required": True},
    "api_id": {"dtype": int, "nullable": True, "default": False, "required": True},
    "season": {"dtype": str, "nullable": False, "default": False, "required": True},
    "team": {"dtype": str, "nullable": False, "default": False, "required": True},
    "position": {"dtype": str, "nullable": False, "default": False, "required": True},
    "shoots": {"dtype": str, "nullable": True, "default": False, "required": False},
    "catches": {"dtype": str, "nullable": True, "default": False, "required": False},
    "birthday": {"dtype": dt.date, "nullable": True, "default": False, "required": True},
    "age": {"dtype": int, "nullable": True, "default": False, "required": True},
    "draft_yr": {"dtype": int, "nullable": True, "default": False, "required": False},
    "draft_rd": {"dtype": str, "nullable": True, "default": False, "required": False},
    "draft_ov": {"dtype": str, "nullable": True, "default": False, "required": False},
    "gp": {"dtype": int, "nullable": True, "default": False, "required": True},
    "toi_all": {"dtype": float, "nullable": True, "default": False, "required": False},
    "xevo_gar": {"dtype": float, "nullable": True, "default": False, "required": False},
    "xevd_gar": {"dtype": float, "nullable": True, "default": False, "required": False},
    "xppo_gar": {"dtype": float, "nullable": True, "default": False, "required": False},
    "xshd_gar": {"dtype": float, "nullable": True, "default": False, "required": False},
    "take_gar": {"dtype": float, "nullable": True, "default": False, "required": True},
    "draw_gar": {"dtype": float, "nullable": True, "default": False, "required": True},
    "xoff_gar": {"dtype": float, "nullable": True, "default": False, "required": False},
    "xdef_gar": {"dtype": float, "nullable": True, "default": False, "required": False},
    "pens_gar": {"dtype": float, "nullable": True, "default": False, "required": False},
    "xgar": {"dtype": float, "nullable": True, "default": False, "required": True},
    "xwar": {"dtype": float, "nullable": True, "default": False, "required": True},
    "xspar": {"dtype": float, "nullable": True, "default": False, "required": True},
}

ind_stats_fields: dict = {key: value for key, value in ind_stats_fields.items() if "api" not in key}

oi_stats_fields: dict = {key: value for key, value in oi_stats_fields.items() if "api" not in key}

stats_fields: dict = {key: value for key, value in stats_fields.items() if "api" not in key}

line_stats_fields: dict = {key: value for key, value in line_stats_fields.items() if "api" not in key}

team_stats_fields: dict = {key: value for key, value in team_stats_fields.items() if "api" not in key}
