name: build

on:
  push:
    branches: ["test"]
  workflow_call:
  workflow_dispatch:

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python: ['3.10', '3.11', '3.12', '3.13']
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - python: '3.10'
            tox: py310
          - python: '3.11'
            tox: py311
          - python: '3.12'
            tox: py312
          - python: '3.13'
            tox: py313
          - os: windows-latest
            os-alt: win
          - os: macos-latest
            os-alt: mac
          - os: ubuntu-latest
            os-alt: lin

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Homebrew (macOS)
        if: matrix.os == 'macos-latest'
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install libomp (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install libomp

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install tox
        run: uv tool install tox --with tox-uv

      - name: Run Test Suite
        run: tox run -e ${{ matrix.tox }}-${{ matrix.os-alt }}
        env:
          CHICKENSTATS_USERNAME: ${{ secrets.CHICKENSTATS_USERNAME }}
          CHICKENSTATS_PASSWORD: ${{ secrets.CHICKENSTATS_PASSWORD }}

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.tox }}-${{ matrix.os-alt }}
          path: .coverage.*
          include-hidden-files: true

  report:
    runs-on: ubuntu-latest
    needs: [test]
    if: always()
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install Coverage CLI
        run: uv tool install coverage

      - name: Download all coverage artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: coverage-*
          merge-multiple: true

      - name: Combine coverage reports
        run: coverage combine

      - name: Generate reports
        run: |
          coverage report
          coverage xml
          coverage html

      - name: Upload htmlcov artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html-report
          path: htmlcov/

      - name: Upload coverage xml
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: ./coverage.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
